import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from '../server.mjs';
import {configuration,publicConfiguration} from '../server/config.mjs';
import {createAuth} from '../server/auth.mjs';
import {createAccess} from '../server/access.mjs';
import {fixtureConfig,fixtureClient,fixtureNotices,fixtureVerify,P1,P2,T1,T2} from './fixtures.mjs';
async function running(fn){const client=fixtureClient(),config=fixtureConfig();const server=createServer({client,config,verify:fixtureVerify,notices:fixtureNotices()});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
  async function login(account='owner'){
    const r=await fetch(base+'/api/auth/challenge'),{nonce}=await r.json(),challenge=r.headers.getSetCookie()[0].split(';')[0];
    const response=await fetch(base+'/api/auth/google',{method:'POST',headers:{Origin:config.origin,'Content-Type':'application/json',Cookie:challenge},body:JSON.stringify({nonce,credential:JSON.stringify({nonce,account})})});
    const data=await response.json();return {status:response.status,data,cookie:response.headers.getSetCookie().find(x=>x.startsWith('casa-session='))?.split(';')[0],csrf:data.csrf};
  }
  const call=(session,path,method='GET',data,extra={})=>fetch(base+'/api/'+path,{method,headers:{Cookie:session?.cookie||'','X-Casa-Csrf':session?.csrf||'',Origin:config.origin,...(data!==undefined?{'Content-Type':'application/json'}:{}),...extra},body:data===undefined?undefined:JSON.stringify(data)});
  try{await fn({client,config,base,login,call});}finally{await new Promise(r=>server.close(r));}
}
test('live is default and demo must be explicit',()=>{assert.equal(configuration({}).mode,'live');assert.equal(configuration({}).ready,false);assert.equal(configuration({APP_MODE:'demo'}).mode,'demo');});
test('public configuration contains no Airtable token, email allowlist or mail credential',()=>{const c=fixtureConfig();const publicText=JSON.stringify(publicConfiguration(c));for(const secret of ['TEST_ONLY_NOT_A_TOKEN','owner@gmail.com','airtableToken','gmailRefreshToken'])assert.ok(!publicText.includes(secret));});
test('invalid origin and malformed bootstrap email prevent activation',()=>{assert.ok(configuration({PUBLIC_ORIGIN:'https://example.test/path',OWNER_EMAILS:'bad'}).missing.includes('PUBLIC_ORIGIN'));assert.ok(configuration({OWNER_EMAILS:'bad'}).missing.includes('OWNER_EMAILS'));});
test('authentication requires a matching nonce and Google-verified email',async()=>{
 const response={setHeader(){}};const auth=createAuth({origin:'https://example.test',clientId:'test',verify:async()=>({nonce:'wrong',sub:'abc',email:'a@gmail.com',email_verified:true})});
 let cookie;response.setHeader=(name,value)=>{cookie=value.split(';')[0];};const {nonce}=auth.challenge(response);
 await assert.rejects(auth.login({headers:{origin:'https://example.test',cookie}},response,{nonce,credential:'token'}),/GOOGLE_IDENTITY_INVALID/);
});
test('challenge is single-use and identity verifier receives the configured audience',async()=>{
 let cookie,audience;const res={setHeader:(n,v)=>{cookie=v.split(';')[0];}},origin='https://example.test';let nonce;
 const auth=createAuth({origin,clientId:'expected-client',verify:async(t,a)=>{audience=a;return {nonce,sub:'s',email:'a@gmail.com',email_verified:true};}});
 ({nonce}=auth.challenge(res));const req={headers:{origin,cookie}},input={nonce,credential:'test'};await auth.login(req,res,input);assert.equal(audience,'expected-client');await assert.rejects(auth.login(req,res,input),/LOGIN_EXPIRED/);
});
test('unauthenticated user cannot retrieve properties',()=>running(async({call})=>assert.equal((await call(null,'state')).status,401)));
test('unlisted Google account is denied; no open signup',()=>running(async({login,client})=>{const r=await login('stranger');assert.equal(r.status,403);assert.equal(client.db['App Access'].length,4);}));
test('manager receives only assigned property and tickets',()=>running(async({login,call})=>{const s=await login('manager');assert.equal(s.status,200);const r=await call(s,'state');const {state}=await r.json();assert.deepEqual(state.properties.map(p=>p.id),[P1]);assert.deepEqual(state.tickets.map(t=>t.id),[T1]);assert.equal(r.headers.get('cache-control'),'no-store');}));
test('viewer cannot create tickets or read people list',()=>running(async({login,call})=>{const s=await login('viewer');assert.equal((await call(s,'tickets','POST',{propertyId:P1,title:'test'})).status,403);assert.equal((await call(s,'members')).status,403);}));
test('cross-property mutation is denied even with valid session and CSRF',()=>running(async({login,call,client})=>{const s=await login('manager');assert.equal((await call(s,'tickets','POST',{propertyId:P2,title:'test'})).status,403);assert.equal((await call(s,`tickets/${T2}/notes`,'POST',{text:'test'})).status,403);assert.equal(client.db['Work Log'].length,0);}));
test('cross-origin and missing CSRF writes are rejected before mutation',()=>running(async({login,call,client})=>{const s=await login();assert.equal((await call(s,'tickets','POST',{propertyId:P1},{Origin:'https://evil.test'})).status,403);assert.equal((await call(s,'tickets','POST',{propertyId:P1},{'X-Casa-Csrf':''})).status,403);assert.equal(client.db.Tickets.length,2);}));
test('reporter creates shared ticket and note but cannot change status',()=>running(async({login,call,client})=>{const s=await login('reporter');const res=await call(s,'tickets','POST',{propertyId:P1,title:'Shared test',description:'A note',priority:'normal',photos:[]});assert.equal(res.status,201);const r=await res.json();assert.ok(r.ticket.id.startsWith('rec'));assert.equal(r.notice.status,'not_configured');assert.equal((await call(s,`tickets/${r.ticket.id}/notes`,'POST',{text:'Updated from phone'})).status,201);assert.equal((await call(s,`tickets/${r.ticket.id}`,'PATCH',{status:'closed',revision:r.ticket.revision})).status,403);assert.equal(client.db['Work Log'].length,1);}));
test('status changes require a current revision and append linked history',()=>running(async({login,call,client})=>{const s=await login('manager');const initial=await(await call(s,'state')).json();const revision=initial.state.tickets[0].revision;const changed=await call(s,`tickets/${T1}`,'PATCH',{status:'in_progress',revision});assert.equal(changed.status,200);assert.equal(client.db['Work Log'][0].fields.Ticket[0],T1);assert.equal((await call(s,`tickets/${T1}`,'PATCH',{status:'closed',revision})).status,409);}));
test('account revocation is enforced on an already-issued session',()=>running(async({login,call,client})=>{const s=await login('viewer');client.db['App Access'].find(r=>r.fields.Role==='Viewer').fields.Active=false;assert.equal((await call(s,'state')).status,403);}));
test('owner grants property-specific access, not a new owner or email invitation',()=>running(async({login,call,client})=>{const s=await login();const data={email:'new@gmail.com',role:'Reporter',properties:[P1],notices:true,language:'es'};assert.equal((await call(s,'members','POST',data)).status,201);const r=client.db['App Access'].at(-1);assert.deepEqual(r.fields.Properties,[P1]);assert.equal(r.fields['Receive Notices'],true);assert.equal((await call(s,'members','POST',{...data,email:'badowner@gmail.com',role:'Owner'})).status,400);assert.equal((await call(s,`members/${r.id}/revoke`,'POST',{})).status,200);}));
test('logout removes server session and uses an HttpOnly cookie',()=>running(async({login,call})=>{const s=await login();assert.equal((await call(s,'auth/logout','POST',{})).status,200);assert.equal((await call(s,'state')).status,401);}));
test('photo upload failure returns saved ticket with explicit warning, not fake success',()=>running(async({login,call,client})=>{client.uploadPhoto=async()=>{throw new Error('offline');};const s=await login();const res=await call(s,'tickets','POST',{propertyId:P1,title:'With photo',description:'',priority:'normal',photos:[{name:'a.png',data:'data:image/png;base64,aGVsbG8='}]});assert.equal(res.status,201);assert.deepEqual((await res.json()).warnings,['PHOTO_UPLOAD_NOT_CONFIRMED']);assert.equal(client.db.Tickets.length,3);}));
test('Google subject binding is authoritative and duplicate subjects fail closed',async()=>{const client=fixtureClient(),access=createAccess(client,['bootstrap@gmail.com']);const identity={sub:'new-sub',email:'bootstrap@gmail.com',authoritative:false};await assert.rejects(access.resolve(identity,{bind:true}),/ACCESS_NOT_GRANTED/);const ctx=await access.resolve({...identity,authoritative:true},{bind:true});assert.equal(ctx.role,'Owner');client.db['App Access'].push(structuredClone(client.db['App Access'].at(-1)));await assert.rejects(access.resolve({...identity,authoritative:true}),/DUPLICATE_ACCESS_RECORD/);});
