import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createNotices,rawMessage,gmailSender} from '../server/notices.mjs';
import {fixtureClient,fixtureConfig,T1} from './fixtures.mjs';
async function withOutbox(fn){const dir=await mkdtemp(path.join(os.tmpdir(),'casa-outbox-'));const client=fixtureClient(),config={...fixtureConfig(),dataDir:dir,mailReady:true,gmailFrom:'sender@gmail.com'};try{await fn({client,config,dir});}finally{await rm(dir,{recursive:true,force:true});}}
test('MIME email rejects header injection and encodes Spanish safely',()=>{assert.throws(()=>rawMessage({from:'a@gmail.com',to:'b@gmail.com',subject:'hello\r\nBcc: secret@gmail.com',text:'test'}));const raw=rawMessage({from:'a@gmail.com',to:'b@gmail.com',subject:'Filtración',text:'Recámara principal'});const decoded=Buffer.from(raw,'base64url').toString();assert.match(decoded,/Content-Transfer-Encoding: base64/);assert.equal(Buffer.from(decoded.split('\r\n\r\n')[1],'base64').toString(),'Recámara principal');});
test('notice text includes the property address, and only approved recipients',()=>withOutbox(async({client,config,dir})=>{const out=createNotices({client,config,send:async()=>''});const result=await out.enqueue(await client.get('Tickets',T1),'New report');assert.equal(result.status,'queued');const rows=JSON.parse(await readFile(path.join(dir,'notices.json')));assert.equal(rows.length,4);assert.match(rows[0].text,/Example Street 1/);assert.match(rows[0].text,/ISS-000001/);assert.ok(rows.every(r=>r.to.endsWith('@gmail.com')));}));
test('Gmail uncertainty is not automatically retried',()=>withOutbox(async({client,config})=>{let calls=0;const out=createNotices({client,config,send:async()=>{calls++;throw new Error('uncertain');}});await out.enqueue(await client.get('Tickets',T1),'New report');await out.drain();await out.drain();assert.equal(calls,4);assert.equal((await out.status()).counts.unknown,4);}));
test('revoked access prevents delivery of an already queued message',()=>withOutbox(async({client,config})=>{let calls=0;const out=createNotices({client,config,send:async()=>{calls++;return 'id';}});await out.enqueue(await client.get('Tickets',T1),'New report');client.db['App Access'].forEach(r=>r.fields.Active=false);await out.drain();assert.equal(calls,0);assert.equal((await out.status()).counts.canceled,4);}));
test('unconfigured email does not claim queued or delivered',()=>withOutbox(async({client,config})=>{const out=createNotices({client,config:{...config,mailReady:false}});assert.deepEqual(await out.enqueue(await client.get('Tickets',T1),'New report'),{status:'not_configured'});}));
test('Gmail adapter refreshes token, sends only raw MIME, caches access token',async()=>{const calls=[];const send=gmailSender({mailReady:true,googleClientId:'c',googleClientSecret:'secret',gmailRefreshToken:'refresh',gmailFrom:'sender@gmail.com'},async(url,opts)=>{calls.push({url,opts});return {ok:true,json:async()=>url.includes('/token')?{access_token:'temporary',expires_in:3600}:{id:'sent-id'}};});for(let i=0;i<2;i++)assert.equal(await send({to:'other@gmail.com',subject:'test',text:'Message'}),'sent-id');assert.equal(calls.length,3);assert.deepEqual(Object.keys(JSON.parse(calls[1].opts.body)),['raw']);assert.equal(calls[1].opts.headers.Authorization,'Bearer temporary');});
test('interrupted sending is durably marked unknown after process restart',()=>withOutbox(async({client,config,dir})=>{await writeFile(path.join(dir,'notices.json'),JSON.stringify([{id:'123',status:'sending'}]));const out=createNotices({client,config,send:async()=>assert.fail('must not resend')});await out.drain();assert.equal((await out.status()).counts.unknown,1);}));
